import type { Disposition, Rational, Tag } from "./primitives.js";
export type Stream = {
    index: number;
    codec_name: string;
    codec_long_name: string;
    profile: string;
    codec_type: string;
    codec_tag_string: string;
    codec_tag: string;
    width: number;
    height: number;
    coded_width: number;
    coded_height: number;
    has_b_frames: number;
    sample_aspect_ratio: Rational;
    display_aspect_ratio: Rational;
    pix_fmt: string;
    level: number;
    color_range: string;
    color_space: string;
    color_transfer: string;
    color_primaries: string;
    chroma_location: string;
    field_order: string;
    sample_fmt: string;
    sample_rate: number;
    channels: number;
    channel_layout: string;
    bits_per_sample: number;
    initial_padding: number;
    id: string;
    r_frame_rate: Rational;
    avg_frame_rate: Rational;
    time_base: Rational;
    start_pts: bigint | null;
    start_time: number | null;
    duration_ts: bigint | null;
    duration: number | null;
    bit_rate: bigint | null;
    bits_per_raw_sample: number;
    nb_frames: bigint | null;
    frame_size: number;
    extradata_size: number;
    disposition: Disposition;
    tags: Tag[];
};
